mqtt:
  ca-cert-path: /home/resources/aws/prepaid_meter_solution/iot_core/AmazonRootCA1.pem
  client-cert-path: /home/resources/aws/prepaid_meter_solution/iot_core/device-certificate.pem.crt
  client-key-path: /home/resources/aws/prepaid_meter_solution/iot_core/private.pem.key